name: "MyNeuralNet"

layers:
  - type: RNN
    input_size: 512
    output_size: 512
    activation: tanh
  
  - type: Dense
    input_size: 512
    output_size: 512
    activation: linear

time_steps: 1

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999

  epochs: 50
  batch_size: 32

metadata:
  author: "James Couch"
  description: "Network configuration with 2 RNN layers, dropout regularization, followed by a Dense layer to reproduce original network behavior"
