name: "OCR"

layers:
  - type: Dense
    input_size: 784
    output_size: 10
    activation: softmax

training:
  optimizer:
    type: adam
    learning_rate: 0.0005  # Reduced to stabilize early training
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 10
  batch_size: 1280  # Smaller batch size for more frequent updates

dataset:
  type: "mnist"
  images: "train-images-idx3-ubyte"
  labels: "train-labels-idx1-ubyte"

metadata:
  author: "James Couch"
  description: "Simple OCR"
