name: "Simple Dense Layer"

layers:
  - type: Dense
    input_size: 512
    output_size: 512
    activation: linear

training:
  optimizer:
    type: adam
    learning_rate: 0.00001
    parameters:
      beta1: 0.9
      beta2: 0.999

  epochs: 5
  batch_size: 10

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Simple Dense Layer"
