name: "Multi Layer Dense NN"

layers:
  - type: Dense
    input_size: 512
    output_size: 512
    activation: tanh

  - type: Dense
    input_size: 512
    output_size: 512
    activation: linear

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999

  epochs: 2
  batch_size: 2

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Multi Layer Dense NN"
