name: "Improved OCR"

layers:
  - type: BatchNormalization
    input_size: 784
    output_size: 784

  - type: Dense
    input_size: 784
    output_size: 256
    activation: relu

  - type: Dropout
    rate: 0.2

  - type: Dense
    input_size: 256
    output_size: 128
    activation: relu

  - type: Dropout
    rate: 0.2

  - type: Dense
    input_size: 128
    output_size: 10
    activation: softmax

training:
  optimizer:
    type: adam
    learning_rate: 0.0005
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 15
  batch_size: 64

dataset:
  type: "mnist"
  images: "train-images-idx3-ubyte"
  labels: "train-labels-idx1-ubyte"

metadata:
  author: "James Couch"
  description: "Enhanced OCR model with BatchNormalization and Dropout"
