name: "RNN"

layers:
  - type: RNN
    input_size: 512
    output_size: 512
    activation: tanh
    time_steps: 5

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999

  epochs: 10
  batch_size: 10

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "RNN"
