name: "Single Dense Layer"

layers:
  - type: Dense
    input_size: 512
    output_size: 512
    activation: linear

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999

  epochs: 1
  batch_size: 1

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Single Dense Layer"
