name: "A Complete Transformer for Text"

layers:
  - type: Input
    name: "input"
    output_size: 128

  - type: Embedding
    name: "token_embedding"
    vocab_size: 30000
    embedding_dim: 128
    input_size: 128
    output_shape: [128, 128]

  - type: PositionalEncoding
    name: "positional_encoding"
    input_shape: [128, 128]
    output_shape: [128, 128]

  - type: MultiHeadAttention
    name: "mha_1"
    input_shape: [128, 128]
    output_shape: [128, 128]
    num_heads: 8
    initializer: xavier

  - type: LayerNormalization
    name: "norm_1"
    input_shape: [128, 128]
    output_shape: [128, 128]
    epsilon: 1e-5

  - type: ResidualConnection
    input_shape: [128, 128]
    output_shape: [128, 128]
    name: "residual_mha"
    from_layer: "positional_encoding"

  - type: Flatten
    name: "flatten_ffn"
    input_shape: [128, 128]
    output_size: 16384

  - type: Dense
    name: "dense_ffn_expand"
    input_size: 16384
    output_size: 32768
    activation: gelu
    initializer: xavier

  - type: Dense
    name: "dense_ffn_reduce"
    input_size: 32768
    output_size: 16384
    activation: linear
    initializer: xavier

  - type: Reshape
    name: "reshape_ffn"
    input_size: 16384
    output_shape: [128, 128]

  - type: LayerNormalization
    name: "norm_ffn"
    input_shape: [128, 128]
    output_shape: [128, 128]
    epsilon: 1e-5

  - type: ResidualConnection
    name: "residual_ffn"
    input_shape: [128, 128]
    output_shape: [128, 128]
    from_layer: "residual_mha"

  - type: Flatten
    name: "flatten_final"
    input_shape: [128, 128]
    output_size: 16384

  - type: Dense
    name: "penultimate_dense"
    input_size: 16384
    output_size: 512
    activation: gelu
    initializer: xavier

  - type: Dense
    name: "classification_head"
    input_size: 512
    output_size: 30000
    activation: softmax
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    accumulation_interval: 4
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 5
  batch_size: 32

dataset:
  type: "text"
  dataset_size: 100000

metadata:
  author: "James Couch"
  description: "A complete transformer architecture explicitly prepared for textual data, including embeddings, positional encoding, and classification head."
