name: "Transformer Basic Test"

layers:
  - type: MultiHeadAttention
    name: "mha_1"
    input_size: 256
    output_size: 256
    num_heads: 1
    sequence_length: 10
    initializer: xavier

  - type: LayerNormalization
    name: "norm_1"
    input_size: 256
    output_size: 256
    epsilon: 1e-5

  - type: ResidualConnection
    input_size: 256
    output_size: 256
    from_layer: "input"

  - type: Dense
    name: "dense_ffn_expand"
    input_size: 256
    output_size: 1024
    activation: gelu
    initializer: he

  - type: Dropout
    rate: 0.1
    input_size: 1024
    output_size: 1024

  - type: Dense
    name: "dense_ffn_reduce"
    input_size: 1024
    output_size: 256
    activation: linear
    initializer: xavier

  - type: LayerNormalization
    name: "norm_ffn"
    input_size: 256
    output_size: 256
    epsilon: 1e-5
    
  - type: ResidualConnection
    input_size: 256
    output_size: 256
    from_layer: "input"

  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear
    initializer: xavier

  - type: ResidualConnection
    input_size: 256
    output_size: 256
    from_layer: "mha_1"

     
  - type: Dense
    name: "final_dense"
    input_size: 256
    output_size: 256  # Adjust as needed for your task
    activation: tanh
    initializer: he

training:
  optimizer:
    type: adam
    learning_rate: 0.0001
    accumulation_interval: 4
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 5
  batch_size: 1

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Basic Transformer with clearly structured Multi-Head Attention, explicit residual connections, and layer normalization."
