name: "Multi Layer Dense NN"

layers:
  - type: Dense
    input_size: 256
    output_size: 256
    activation: tanh
    
  - type: VectorToSequence
    time_steps: 10
    input_size: 256
    output_size: 256
        
  - type: SequenceToVector
    time_steps: 10
    input_size: 256
    output_size: 256

  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear

training:
  optimizer:
    type: adam
    learning_rate: 0.0001
    parameters:
      beta1: 0.9
      beta2: 0.999

  epochs: 2
  batch_size: 2

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Multi Layer Dense NN"
